### ISSUE TITLE
변수 스타일이 일관적이지 않은 상태입니다.

### ISSUE THREAD

**Issue by ej31** [bB-Ksb/MMS#2]
https://github.com/bB-Ksb/MMS/blob/39a2e5e207b1674bf73111672886fbf49b325ef2/maple_model.py#L11

- 변수 스타일을 맞춰야해요
- 클래스 내 인스턴수는 스네이크 케이스를 권장해요
- 그리고 상수 값으로만 쓰이는 것은 가급적 클래스 변수 위치에 놓고 스크리밍 케이스로 관리하는 걸 개인적으로 권장합니다.

```python

class MapleModel:
        MAPLE_ROOT_URL = "https://maplestory.nexon.com"
```

- URI 주소는 마지막에 슬래시로 끝나지 않게 스타일을 유지해보세요
- 나중에 주소 관리 할 일이 많습니다.
- 이 때 슬래시로 시작하는 스타일이 일관되지 않으면 변수를 쓸 때마다 매번 확인해야 합니다.
- 윈도우 시스템 관리 할 때는 슬래시에 해당하는 문구 (\) 가 여러개면 작동을 안하는 등의 이슈가 생길 수 있으니 스타일을 하나로 맞추는게 좋습니다
- 더 나아가서 슬래시 갯수가 안맞으면 접근을 거부하는 웹서버도 있습니다. (설정이 가능해요)

**Comment by bB-Ksb** [comment]
다음과 같은 형식으로 수정하였습니다.
```python
class MapleModel:
    maple_home_url = "https://maplestory.nexon.com"
    def __init__(self):
        # self.MapleHome_URL = "https://maplestory.nexon.com/"
        pass
```

**Comment by bB-Ksb** [comment]
다음과 같이 코드 수정하였습니다:
```python
class MapleModel:
    maple_home_url = "https://maplestory.nexon.com"
    def __init__(self):
        # self.MapleHome_URL = "https://maplestory.nexon.com/"
        pass
```
